---
downloads: ~/.ansible-downloads/

configure_dotfiles: no

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - python3
  # 7Zip for OSX - sometimes those encrypted zips make unzip sad
  - p7zip
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - intellij-idea
  - macvim
  - sequel-pro
  - skitch
  - spotify
  - transmit
  - vagrant
  # Virtualbox fails on the first install as the application needs to be whitelisted inside OSX. Once failed, approve the app rerun the play and all is good
  - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1295203466, name: "Remote Desktop 10" }
  - { id: 803453959, name: "Slack" }
mas_email: "george.wilson@automationlogic.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Dirty bodge to avoid using package with sudo (which proxies to homebrew and then as sudo fails)
intellij_plugins_python_major_version: 1
