---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    - name: get the username running the deploy for IntelliJ Setup
      become: false
      local_action: command whoami
      register: current_username
      changed_when: false

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: gantsign.intellij-plugins
      intellij_plugins_intellij_home: '/Applications/IntelliJ\ IDEA.app'
      intellij_plugins_intellij_user_dirname: '/Users/{{ current_username.stdout_lines[0] }}/Library/Preferences/IntelliJIdea2019.3'
      users:
        - username: "{{ current_username.stdout_lines[0] }}"
          intellij_plugins:
            - intellij-ansible

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
